### ISSUE TITLE
About screen

### ISSUE THREAD

**Issue by AdamWang00** [FullStackAtBrownTeam/project-bsr-app#3]
Creating the About screen is a good starting point for creating styles and templates to be reused on other screens.

**Comment by swetabhch** [comment]
I've established the appropriate styles for headings, text, and the overall view that wraps the page for both the light and dark modes. How do I assume information about display mode will be made available? I can currently think of it being sent through as props from the navigation bar, but not completely sure how that would work. If I can make that short update, the About screen should effectively be done. Thank you!
